config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'home#index'
  get '/admins' , to: 'admins/home#index', as: 'admin_home'
  get '/admins/:id' , to: 'admins/home#show', as: 'admin_status'
  post '/admins/activate/:id' , to: 'admins/home#activate', as: 'admin_activate'
  post '/admins/inactivate/:id' , to: 'admins/home#inactivate', as: 'admin_inactivate'
  get '/admins/blog/:blog_id' , to: 'admins/home#blog', as: 'admin_blog'
  delete '/admins/blog/:blog_id/:id' , to: 'admins/home#articledestroy', as: 'admin_destroy_article'
  get '/admins/:blog_id/article/:article_id' , to: 'admins/home#article', as: 'admin_article'
  delete '/admins/:blog_id/article/:article_id/:id' , to: 'admins/home#commentdestroy', as: 'admin_destroy_comment'
  # get '/admins/:blog_id/article/:article_id' , to: 'admins/home#comment', as: 'admin_comment'
  devise_for :admins , controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }
  resources :blog do
    resources :articles do
      resources :comment
      resources :like
    end
  end
  post 'avatar', to: 'blog#avatar', as: 'save_avatar'
  get '/public/:blog_id' , to: 'public#index', as: 'public_blog'
  get '/public/:blog_id/:id' , to: 'public#show', as: 'public_article'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/elements/_adminheader.html.erb
<!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top bs-docs-nav">
      <div class="container">
        <div class="navbar-header responsive-logo">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><%= image_tag("logo.png") %></a>
        </div>
        <ul class="nav navbar-nav navbar-right navbar-sign-in">
            <li><%= link_to 'ログアウト', destroy_admin_session_path %></li>
        </ul>
      </div>
    </nav><!-- Fixed navbar -->

app/views/elements/_adminloginheader.html.erb
<!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top bs-docs-nav">
      <div class="container">
        <div class="navbar-header responsive-logo">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><%= image_tag("logo.png") %></a>
        </div>
      </div>
    </nav><!-- Fixed navbar -->

app/views/elements/_homeblog.html.erb
<div class="container-fliud home_bg">
    <%= image_tag("home-bg.jpg", :class => "img-responsive") %>
    <div class="label-home">
        <h1>Four Hundred</h1>
        <h5>Express your self and share to the world</h5>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-lg-2 col-md-1 mx-auto">
        </div>
        <div class="col-lg-8 col-md-10 mx-auto">
            <% @blogs.each do |blog| %>
                <div class="blog_wrapper">
                    <%= link_to public_blog_path(blog.url) do%>
                        <h3 class="blog_title">
                            <%= blog.title %>
                        </h3>
                        <p class="blog_des">
                            <%= blog.description %>
                        </p>
                    <% end %>
                    <p class="blog_author">
                        Author By <span><%= blog.username %></span>
                    </p>
                </div>
                <hr />
            <% end %>
        </div>
        <div class="col-lg-2 col-md-1 mx-auto">
        </div>
    </div>
</div>

app/views/elements/_homelogin.html.erb
<div class="container" style="padding-top:40px;" role="main">
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="section-header">
                <%= link_to 'Twitterログイン', user_twitter_omniauth_authorize_path, class: "btn btn-primary" %>
                <%= link_to 'facebookログイン', user_facebook_omniauth_authorize_path, class: "btn btn-primary" %>
            </div>        
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="login-wrapper">
                
                <div class="section-header">
                    <h3>SIGN IN FORM</h3>
                </div>
                <%= form_for(:user, :url => user_session_path) do |f| %>
                    <div class="form-group">
                      <%= f.label :email %><br />
                      <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
                    </div>
                      
                    <div class="form-group">
                      <%= f.label :password %><br />
                      <%= f.password_field :password, autocomplete: "current-password", class: "form-control" %>
                    </div>
                  
                    <% if Devise.mappings[:user].rememberable? %>
                        <div class="form-group">
                            <%= f.check_box :remember_me %>
                            <%= f.label :remember_me %>
                        </div>
                    <% end %>
                      
                    <div class="actions">
                      <%= f.submit "Log in", class: "btn btn-primary" %>
                    </div>
                <% end %>
            </div>
        </div>
        <div class="col-md-6 col-sm-6 col-xs-12">
            <div class="login-wrapper">
                <div class="section-header">
                    <h3>SIGN UP</h3>
                </div>
                <%= form_for(:user, url: user_registration_path) do |f| %>      
                    <div class="form-group">
                      <%= f.label :email %><br />
                      <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
                    </div>
                      
                    <div class="form-group">
                        <%= f.label :password %>
                      <% if @minimum_password_length %>
                      <em>(<%= @minimum_password_length %> characters minimum)</em>
                      <% end %><br />
                      <%= f.password_field :password, autocomplete: "new-password", class: "form-control" %>
                    </div>                      
                    <div class="form-group">
                      <%= f.label :password_confirmation %><br />
                      <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control" %>
                    </div>
                      
                    <div class="actions">
                      <%= f.submit "Sign up", class: "btn btn-primary" %>
                    </div>
                  <% end %>
                </div>
        </div>        
    </div>
</div>

app/views/elements/_homesignin.html.erb
<div class="container theme-showcase" role="main">
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
        <h1>Home sign in</h1>
        <p>Find me in app/views/home/index.html.erb</p>
    </div>
</div>

app/views/elements/_loginheader.html.erb
<!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top bs-docs-nav">
      <div class="container">
        <div class="navbar-header responsive-logo">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><%= image_tag("logo.png") %></a>
        </div>
        <ul class="nav navbar-nav navbar-right navbar-sign-in">
          <li><%= link_to 'Twitterログイン', user_twitter_omniauth_authorize_path %></li>
          <li><%= link_to 'facebookログイン', user_facebook_omniauth_authorize_path %></li>        
          <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">ログイン<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <%= render "elements/signinform" %>
            </ul>
          </li>
          <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">サインアップ<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <%= render "elements/signupform" %>
            </ul>
          </li>
        </ul>
      </div>
    </nav>

app/views/elements/_signinform.html.erb
<%= form_for(:user, :url => user_session_path) do |f| %>
    <div class="form-group">
        <%= f.label  :メール %><br />
        <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
    </div>
  
    <div class="form-group">
        <%= f.label :パスワード %><br />
        <%= f.password_field :password, autocomplete: "current-password", class: "form-control" %>
    </div>

    <% if Devise.mappings[:user].rememberable? %>
        <div class="form-group">
            <%= f.check_box :remember_me %>
            <%= f.label :覚える %>
        </div>
    <% end %>
  
    <div class="actions">
        <%= f.submit "ログイン", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/elements/_signinheader.html.erb
<!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top bs-docs-nav">
      <div class="container">
        <div class="navbar-header responsive-logo">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><%= image_tag("logo.png") %></a>
        </div>
        <ul class="nav navbar-nav navbar-right navbar-sign-in">
            <li><%= link_to 'ブロック', blog_index_path %></li>
            <li><%= link_to 'ログアウト', destroy_user_session_path %></li>
        </ul>
      </div>
    </nav><!-- Fixed navbar -->

app/views/elements/_signupform.html.erb
<%= form_for(:user, url: user_registration_path) do |f| %>      
    <div class="form-group">
      <%= f.label :メール %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
    </div>
      
    <div class="form-group">
        <%= f.label :パスワード %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "new-password", class: "form-control" %>
    </div>                      
    <div class="form-group">
      <%= f.label :パスワード確認 %><br />
      <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control" %>
    </div>
      
    <div class="actions">
      <%= f.submit "サインアップ", class: "btn btn-primary" %>
    </div>
<% end %>