config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'home#index'
  get '/admins' , to: 'admins/home#index', as: 'admin_home'
  get '/admins/:id' , to: 'admins/home#show', as: 'admin_status'
  post '/admins/activate/:id' , to: 'admins/home#activate', as: 'admin_activate'
  post '/admins/inactivate/:id' , to: 'admins/home#inactivate', as: 'admin_inactivate'
  get '/admins/blog/:blog_id' , to: 'admins/home#blog', as: 'admin_blog'
  delete '/admins/blog/:blog_id/:id' , to: 'admins/home#articledestroy', as: 'admin_destroy_article'
  get '/admins/:blog_id/article/:article_id' , to: 'admins/home#article', as: 'admin_article'
  delete '/admins/:blog_id/article/:article_id/:id' , to: 'admins/home#commentdestroy', as: 'admin_destroy_comment'
  # get '/admins/:blog_id/article/:article_id' , to: 'admins/home#comment', as: 'admin_comment'
  devise_for :admins , controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }
  resources :blog do
    resources :articles do
      resources :comment
      resources :like
    end
  end
  post 'avatar', to: 'blog#avatar', as: 'save_avatar'
  get '/public/:blog_id' , to: 'public#index', as: 'public_blog'
  get '/public/:blog_id/:id' , to: 'public#show', as: 'public_article'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admins/home_controller.rb
class Admins::HomeController < ApplicationController
    before_action :authenticate_admin! #autothication for routing
    def index
        @users = User.joins("INNER JOIN blogs ON users.id = blogs.user_id").select("users.* , blogs.id as blog_id, blogs.url as blog_url, blogs.username as blog_username ")
    end

    def show
        @users = User.joins("INNER JOIN blogs ON users.id = blogs.user_id").select("users.* , blogs.id as blog_id, blogs.url as blog_url, blogs.username as blog_username").where("users.status =#{params[:id]}")
    end

    def blog
        @blog = Blog.find_by(id: params[:blog_id]) #getting article that not deleted
        @articles = Article.where("blog_id = #{params[:blog_id]} and articles.status != 0") #getting article that not deleted
    end

    def articledestroy
		@article = Article.find(params[:id])
		if(@article.update(:status => 0))
			redirect_to admin_blog_path(@article.blog_id)
        else
			redirect_to admin_blog_path(@article.blog_id)
        end 
    end    
    
    def article
        @article = Article.find(params["article_id"])
        @blog = Blog.joins(:user).where("users.status = 1 and (blogs.url = '#{params["blog_id"]}' or blogs.id = '#{params["blog_id"]}')").first
        @comments = Comment.joins("LEFT JOIN articles ON comments.article_id = articles.id LEFT JOIN blogs ON comments.user_id = blogs.user_id  LEFT JOIN users ON comments.user_id = users.id ").select("comments.*, blogs.username as username, users.avatar").where("articles.id = #{params["article_id"]}")

    end

    def commentdestroy

        @comment = Comment.find(params[:id])
        @comment.destroy
        redirect_to admin_article_path(params[:blog_id], params[:article_id])
    end

    def inactivate
        @user = User.find(params[:id])
        if(@user.update(:status => 0))
            UsersMailer.inactive(@user).deliver
			redirect_to admin_home_path
        else
			redirect_to admin_home_path
        end 
    end

    def activate
        @user = User.find(params[:id])
        UsersMailer.active(@user).deliver
        if(@user.update(:status => 1))
			redirect_to admin_home_path
        else
			redirect_to admin_home_path
        end 
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  PER = 1
  def index
    @blogs = Blog.joins("LEFT JOIN articles ON blogs.id = articles.blog_id LEFT JOIN users ON blogs.user_id = users.id ").group(:id).select("blogs.*, count(articles.id) as articles_count").where("articles.status = 1 and users.status <> 0")
    @blogs = Kaminari.paginate_array(@blogs).page(params[:page]).per(1)
  end
end

app/helpers/admins/home_helper.rb
module Admins::HomeHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admins/home/article.html.erb
<%= render "elements/adminheader" %>
<div class="container theme-showcase  main-body" role="main">
    <div class="row">
        <div class="col-sm-12 col-md-12 col-xs-12">
            <h1>記事タイトル：<%= @article.title %></h1>
        </div>
        <div class="col-sm-12 col-md-12 col-xs-12">
        <table class="table table-striped">
            <tr>
                <th>ユーザー名</th>
                <th>内容</th>
                <th>Action</th>
            </tr>                
            <% @comments.each do |comment| %>
                <tr>
                    <td><%= comment.username %></td>
                    <td><%= comment.body %></td>
                    <td class="action-data">
                        <%= link_to content_tag(:i, '', class: 'fa fa-trash'), admin_destroy_comment_path(@blog.id, @article.id, comment.id), method: :delete, data: {confirm: 'Are You Sure'}  %>
                    </td>
                </tr>
            <% end %>
        </table>
    </div>        
    </div>
</div>

app/views/admins/home/blog.html.erb
<%= render "elements/adminheader" %>
<div class="container theme-showcase  main-body" role="main">
    <div class="row">
        <div class="col-sm-12 col-md-12 col-xs-12">
            <table class="table table-striped">
                <tr>
                    <th>タイトル</th>
                    <th>ステータス</th>
                    <th>Action</th>
                </tr>                
                <% @articles.each do |article| %>
                    <tr>
                        <td><%= article.title %></td>
                        <td><%= article.status == 1? "PUBLIC" : "PRIVATE" %></td>
                        <td class="action-data">
                            <%= link_to content_tag(:i, '', class: 'fa fa-eye'), public_article_path(@blog.url, article.id) %>
                            <%= link_to content_tag(:i, '', class: 'fa fa-trash'), admin_destroy_article_path(@blog.id, article.id), method: :delete, data: {confirm: 'Are You Sure'}  %>
                            <%= link_to content_tag(:i, '', class: 'fa fa-comments'), admin_article_path(@blog.id, article.id)  %>                            
                        </td>
                    </tr>
                <% end %>
            </table>
        </div>
    </div>

    
</div>

app/views/admins/home/index.html.erb
<%= render "elements/adminheader" %>
<div class="container theme-showcase  main-body" role="main">
    <ul class="nav nav-tabs">
        <li class="active"><%= link_to 'すべて', admin_home_path %></li>
        <li><%= link_to '活動中', admin_status_path("1") %></li>
        <li><%= link_to '非活動中', admin_status_path("0") %></li>
    </ul>
    
    <%= render "elements/admin/usersdata" %>
</div>

app/views/admins/home/show.html.erb
<%= render "elements/adminheader" %>
<div class="container theme-showcase  main-body" role="main">
    <ul class="nav nav-tabs">
        <li><%= link_to 'すべて', admin_home_path %></li>
        <% if params['id'] == "0" %>
            <li ><%= link_to '活動中', admin_status_path("1") %></li>
            <li class="active"><%= link_to '非活動中', admin_status_path("0") %></li>
        <% else %>
            <li class="active"><%= link_to '活動中', admin_status_path("1") %></li>
            <li><%= link_to '非活動中', admin_status_path("0") %></li>
        <% end %>

    </ul>
    <%= render "elements/admin/usersdata" %>
</div>