config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root 'home#index'
  get '/admins' , to: 'admins/home#index', as: 'admin_home'
  get '/admins/:id' , to: 'admins/home#show', as: 'admin_status'
  post '/admins/activate/:id' , to: 'admins/home#activate', as: 'admin_activate'
  post '/admins/inactivate/:id' , to: 'admins/home#inactivate', as: 'admin_inactivate'
  get '/admins/blog/:blog_id' , to: 'admins/home#blog', as: 'admin_blog'
  delete '/admins/blog/:blog_id/:id' , to: 'admins/home#articledestroy', as: 'admin_destroy_article'
  get '/admins/:blog_id/article/:article_id' , to: 'admins/home#article', as: 'admin_article'
  delete '/admins/:blog_id/article/:article_id/:id' , to: 'admins/home#commentdestroy', as: 'admin_destroy_comment'
  # get '/admins/:blog_id/article/:article_id' , to: 'admins/home#comment', as: 'admin_comment'
  devise_for :admins , controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }
  resources :blog do
    resources :articles do
      resources :comment
      resources :like
    end
  end
  post 'avatar', to: 'blog#avatar', as: 'save_avatar'
  get '/public/:blog_id' , to: 'public#index', as: 'public_blog'
  get '/public/:blog_id/:id' , to: 'public#show', as: 'public_article'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :aricles

  validates :title, presence: true, length: {minimum: 5}
  validates :description, presence: true, length: {minimum: 5}
  validates :url, presence: true, uniqueness: true, length: {minimum: 5}
  validates :username, presence: true, uniqueness: true, length: {minimum: 5}
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
    before_action :authenticate_user!
    def index
        if session["imageSuccess"] != nil
            if session["imageSuccess"] == true
                @successImage = true
                session["imageSuccess"] = nil
            else
                @successImage = session["imageSuccess"] 
                session["imageSuccess"] = nil
            end                
        end
 
        if user_signed_in? 
            @userImage = User.find(current_user.id)

            @check = Blog.find_by(user_id: current_user.id)
            if @check != nil
                @blog = @check
                @articles = Article.where("blog_id = #{@blog.id}").order(:created_at).limit(10)
            else
                @blog = Blog.new
            end
        else
            redirect_to root_path
        end
    end

    def create
        #render plain: params[:post].inspect
        @blog = Blog.find_by(user_id: current_user.id)
        if user_signed_in? 
            @userImage = User.find(current_user.id)

            @check = Blog.find_by(user_id: current_user.id)
            if @check != nil
                 @articles = Article.where("blog_id = #{@blog.id}").order(:created_at).limit(10)
            else
                @articles = []
            end
        else
            redirect_to root_path
        end        
        if @blog != nil
            if(@blog.update(blog_params))
                @success = true;
                render 'index'
            else
                @success = false;
                render 'index'
            end    
        else
            @blog = Blog.new(blog_params)
            @blog.user_id = current_user.id
            if(@blog.save())
                @success = true;
                render 'index'
            else
                @success = false;
                render 'index'
            end    
        end
    end

    def avatar
        @user = User.find(current_user.id)

        if @user.update(avatar_params)
            session["imageSuccess"] = true
            redirect_to blog_index_path
        else
            if @user.errors.messages[:avatar][0] != nil
                session["imageSuccess"] = @user.errors.messages[:avatar][0]
            else
                session["imageSuccess"] = "UPLOAD FAILED"
            end    
            redirect_to blog_index_path
        end
    end
    
    private def blog_params
        params.require(:blog).permit(:title, :description, :url, :username)
    end    

    private def avatar_params
        params.require(:user).permit(:avatar)
    end    

    def show
		@blog = Blog.joins(:user).where('users.status = 1 and blogs.url = "' + params["id"] +'"').first
        if @blog != nil
			@articles = Article.where("blog_id = #{@blog.id} and articles.status != 0")
		else
			redirect_to root
		end	
    end
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blog/index.html.erb
    <%= render "elements/signinheader" %>
    <div class="container theme-showcase main-body" role="main">
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="row">
        <div class="col-sm-4 col-md-4 col-xs-12">
        <% if @successImage != nil %>  
            <% if @successImage == true %>
                <div class="alert alert-success">AVATAR UPLLOAD SUCCESS</div>
            <% else %>  
                <div class="alert alert-danger"><%= @successImage %></div>
            <% end %>    
        <% end %>  
        <%= form_for :user, url: save_avatar_path do |f| %>
            <div class="input-group">
                <% if @userImage.avatar? && @userImage.avatar != '' %>  
                    <%= image_tag(@userImage.avatar_url , :class => "img-responsive") %>
                <% else %>    
                    <%= image_tag('blank_profile.png' , :class => "img-responsive") %>
                <% end %>    
            </div>
            <div class="display_hide">
                <%= f.file_field :avatar, multiple: false %>
            </div>
            <div class="input-group pt-15">
              <input type="text" id="AvatarCover" class="form-control" placeholder="select file...">
              <span class="input-group-btn"><button type="button" class="btn btn-info" onclick="$('input[id=user_avatar]').click();">Browse</button></span>
            </div>            
            <div class="input-group pt-15">
                <%= f.submit "登録" , :class => 'btn btn-primary'  %>
            </div>
        <% end %>
        </div>
        <div class="col-sm-8 col-md-8 col-xs-12 for_blog">
            <%= form_for :blog, :html => { :multipart => true }, url: blog_index_path do |f| %>   
                <% if @success != nil %>                
                    <% if @success == true %>
                        <div class="alert alert-success">Update Sucess</div>            
                    <% end %>
                <% end %>
                <% @blog.errors.full_messages.each do |msg| %>
                    <% @blog.errors.full_messages.each do |msg| %>
                        <div class="alert alert-danger"><%= msg %></div>
                    <% end %>                
                <% end %>                
                <p>
                    <%= f.label :タイトル %><br>
                    <%= f.text_field(:title, {:class => "form-control"}) %>
                </p>
                <p>
                    <%= f.label :説明 %><br>
                    <%= f.text_area(:description, {:class => "form-control"}) %>
                </p>
                <p>
                    <%= f.label :url %><br>
                        <div class="input-group">
                            <span class="input-group-addon" id="basic-addon3">https://example.com/public/</span>
                            <%= f.text_field(:url, {:class => "form-control"}) %>
                        </div>
                </p>
                <p>
                    <%= f.label :ユーザー名 %><br>
                    <%= f.text_field(:username, {:class => "form-control"}) %>
                </p>
                <p>
                    <%= f.submit "登録" , :class => 'btn btn-primary'  %>
                </p>
            <% end %>
        </div>
    </div>
    <% if @blog.url? %>
        <hr/>
        <div class="row">
            <div class="col-sm-12 col-md-12 col-xs-12">
                <%= link_to '新しい記事登録' , new_blog_article_path(@blog.url) , :class => "btn btn-primary pull-right" %>
                <h1>記事一覧</h1>        
                <table class="table table-striped">
                    <tr>
                        <th>タイトル</th>
                        <th>ステータス</th>
                        <th>Action</th>
                    </tr>                
                    <% @articles.each do |article| %>
                        <tr>
                            <td><%= article.title %></td>
                            <td><%= article.status == 1? "PUBLIC" : "PRIVATE" %></td>
                            <td class="action-data">
                                <%= link_to content_tag(:i, '', class: 'fa fa-eye'), blog_article_path(@blog.url, article.id) %>
                                <%= link_to content_tag(:i, '', class: 'fa fa-edit'), edit_blog_article_path(@blog.id, article.id) %>
                                <%= link_to content_tag(:i, '', class: 'fa fa-trash'), blog_article_path(@blog.url, article.id), method: :delete, data: {confirm: 'Are You Sure'}  %>
                                <%= link_to content_tag(:i, '', class: 'fa fa-comments'), blog_article_comment_index_path(@blog.url, article.id)  %>
                            </td>
                        </tr>
                    <% end %>
                </table>
                <%= link_to "記事一覧を見る" , blog_articles_path(@blog.url), {:class => "btn btn-primary"} %>
            </div>
        </div>
    <% end %>     
</div>  

<script>
  $('input[id=user_avatar]').change(function() {
    $('#AvatarCover').val($(this).val());
  });
</script>

app/views/blog/show.html.erb
<%= render "elements/signinheader" %>
<div class="container theme-showcase" role="main">
    <div class="row">
        <div class="col-sm-12 col-md-12 col-xs-12">
            <h1>list articles</h1>
            <% @articles.each do |article| %>
                <div class="article_card">
                    <div class="article_title">
                        
                    </div>
                </div>
            <% end %>
        </div>
    </div>  
</div>